#include "stdafx.h"
#include "DXHelper11.h"
DXHelper11::DXHelper11()
{
}

DXHelper11::~DXHelper11()
{
}

DXGI_FORMAT DXHelper11::GetIndexBufferFormat(RenderEngine::ORBIT_FORMAT indexFormat) const
{
	switch (indexFormat)
	{
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_UNKNOWN:						return DXGI_FORMAT_UNKNOWN;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R32G32B32A32_TYPELESS:		return DXGI_FORMAT_R32G32B32A32_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R32G32B32A32_FLOAT:			return DXGI_FORMAT_R32G32B32A32_FLOAT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R32G32B32A32_UINT:			return DXGI_FORMAT_R32G32B32A32_UINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R32G32B32A32_SINT:			return DXGI_FORMAT_R32G32B32A32_SINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R32G32B32_TYPELESS:			return DXGI_FORMAT_R32G32B32_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R32G32B32_FLOAT:				return DXGI_FORMAT_R32G32B32_FLOAT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R32G32B32_UINT:				return DXGI_FORMAT_R32G32B32_UINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R32G32B32_SINT:				return DXGI_FORMAT_R32G32B32_SINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R16G16B16A16_TYPELESS:		return DXGI_FORMAT_R16G16B16A16_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R16G16B16A16_FLOAT:			return DXGI_FORMAT_R16G16B16A16_FLOAT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R16G16B16A16_UNORM:			return DXGI_FORMAT_R16G16B16A16_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R16G16B16A16_UINT:			return DXGI_FORMAT_R16G16B16A16_UINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R16G16B16A16_SNORM:			return DXGI_FORMAT_R16G16B16A16_SNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R16G16B16A16_SINT:			return DXGI_FORMAT_R16G16B16A16_SINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R32G32_TYPELESS:				return DXGI_FORMAT_R32G32_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R32G32_FLOAT:					return DXGI_FORMAT_R32G32_FLOAT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R32G32_UINT:					return DXGI_FORMAT_R32G32_UINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R32G32_SINT:					return DXGI_FORMAT_R32G32_SINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R32G8X24_TYPELESS:			return DXGI_FORMAT_R32G8X24_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_D32_FLOAT_S8X24_UINT:			return DXGI_FORMAT_D32_FLOAT_S8X24_UINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R32_FLOAT_X8X24_TYPELESS:		return DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_X32_TYPELESS_G8X24_UINT:		return DXGI_FORMAT_X32_TYPELESS_G8X24_UINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R10G10B10A2_TYPELESS:			return DXGI_FORMAT_R10G10B10A2_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R10G10B10A2_UNORM:			return DXGI_FORMAT_R10G10B10A2_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R10G10B10A2_UINT:				return DXGI_FORMAT_R10G10B10A2_UINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R11G11B10_FLOAT:				return DXGI_FORMAT_R11G11B10_FLOAT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R8G8B8A8_TYPELESS:			return DXGI_FORMAT_R8G8B8A8_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R8G8B8A8_UNORM:				return DXGI_FORMAT_R8G8B8A8_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R8G8B8A8_UNORM_SRGB:			return DXGI_FORMAT_R8G8B8A8_UNORM_SRGB;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R8G8B8A8_UINT:				return DXGI_FORMAT_R8G8B8A8_UINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R8G8B8A8_SNORM:				return DXGI_FORMAT_R8G8B8A8_SNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R8G8B8A8_SINT:				return DXGI_FORMAT_R8G8B8A8_SINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R16G16_TYPELESS:				return DXGI_FORMAT_R16G16_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R16G16_FLOAT:					return DXGI_FORMAT_R16G16_FLOAT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R16G16_UNORM:					return DXGI_FORMAT_R16G16_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R16G16_UINT:					return DXGI_FORMAT_R16G16_UINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R16G16_SNORM:					return DXGI_FORMAT_R16G16_SNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R16G16_SINT:					return DXGI_FORMAT_R16G16_SINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R32_TYPELESS:					return DXGI_FORMAT_R32_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_D32_FLOAT:					return DXGI_FORMAT_D32_FLOAT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R32_FLOAT:					return DXGI_FORMAT_R32_FLOAT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R32_UINT:						return DXGI_FORMAT_R32_UINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R32_SINT:						return DXGI_FORMAT_R32_SINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R24G8_TYPELESS:				return DXGI_FORMAT_R24G8_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_D24_UNORM_S8_UINT:			return DXGI_FORMAT_D24_UNORM_S8_UINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R24_UNORM_X8_TYPELESS:		return DXGI_FORMAT_R24_UNORM_X8_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_X24_TYPELESS_G8_UINT:			return DXGI_FORMAT_X24_TYPELESS_G8_UINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R8G8_TYPELESS:				return DXGI_FORMAT_R8G8_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R8G8_UNORM:					return DXGI_FORMAT_R8G8_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R8G8_UINT:					return DXGI_FORMAT_R8G8_UINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R8G8_SNORM:					return DXGI_FORMAT_R8G8_SNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R8G8_SINT:					return DXGI_FORMAT_R8G8_SINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R16_TYPELESS:					return DXGI_FORMAT_R16_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R16_FLOAT:					return DXGI_FORMAT_R16_FLOAT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_D16_UNORM:					return DXGI_FORMAT_D16_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R16_UNORM:					return DXGI_FORMAT_R16_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R16_UINT:						return DXGI_FORMAT_R16_UINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R16_SNORM:					return DXGI_FORMAT_R16_SNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R16_SINT:						return DXGI_FORMAT_R16_SINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R8_TYPELESS:					return DXGI_FORMAT_R8_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R8_UNORM:						return DXGI_FORMAT_R8_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R8_UINT:						return DXGI_FORMAT_R8_UINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R8_SNORM:						return DXGI_FORMAT_R8_SNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R8_SINT:						return DXGI_FORMAT_R8_SINT;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_A8_UNORM:						return DXGI_FORMAT_A8_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R1_UNORM:						return DXGI_FORMAT_R1_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R9G9B9E5_SHAREDEXP:			return DXGI_FORMAT_R9G9B9E5_SHAREDEXP;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R8G8_B8G8_UNORM:				return DXGI_FORMAT_R8G8_B8G8_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_G8R8_G8B8_UNORM:				return DXGI_FORMAT_G8R8_G8B8_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_BC1_TYPELESS:					return DXGI_FORMAT_BC1_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_BC1_UNORM:					return DXGI_FORMAT_BC1_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_BC1_UNORM_SRGB:				return DXGI_FORMAT_BC1_UNORM_SRGB;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_BC2_TYPELESS:					return DXGI_FORMAT_BC2_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_BC2_UNORM:					return DXGI_FORMAT_BC2_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_BC2_UNORM_SRGB:				return DXGI_FORMAT_BC2_UNORM_SRGB;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_BC3_TYPELESS:					return DXGI_FORMAT_BC3_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_BC3_UNORM:					return DXGI_FORMAT_BC3_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_BC3_UNORM_SRGB:				return DXGI_FORMAT_BC3_UNORM_SRGB;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_BC4_TYPELESS:					return DXGI_FORMAT_BC4_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_BC4_UNORM:					return DXGI_FORMAT_BC4_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_BC4_SNORM:					return DXGI_FORMAT_BC4_SNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_BC5_TYPELESS:					return DXGI_FORMAT_BC5_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_BC5_UNORM:					return DXGI_FORMAT_BC5_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_BC5_SNORM:					return DXGI_FORMAT_BC5_SNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_B5G6R5_UNORM:					return DXGI_FORMAT_B5G6R5_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_B5G5R5A1_UNORM:				return DXGI_FORMAT_B5G5R5A1_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_B8G8R8A8_UNORM:				return DXGI_FORMAT_B8G8R8A8_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_B8G8R8X8_UNORM:				return DXGI_FORMAT_B8G8R8X8_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_R10G10B10_XR_BIAS_A2_UNORM:	return DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_B8G8R8A8_TYPELESS:			return DXGI_FORMAT_B8G8R8A8_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_B8G8R8A8_UNORM_SRGB:			return DXGI_FORMAT_B8G8R8A8_UNORM_SRGB;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_B8G8R8X8_TYPELESS:			return DXGI_FORMAT_B8G8R8X8_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_B8G8R8X8_UNORM_SRGB:			return DXGI_FORMAT_B8G8R8X8_UNORM_SRGB;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_BC6H_TYPELESS:				return DXGI_FORMAT_BC6H_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_BC6H_UF16:					return DXGI_FORMAT_BC6H_UF16;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_BC6H_SF16:					return DXGI_FORMAT_BC6H_SF16;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_BC7_TYPELESS:					return DXGI_FORMAT_BC7_TYPELESS;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_BC7_UNORM:					return DXGI_FORMAT_BC7_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_BC7_UNORM_SRGB:				return DXGI_FORMAT_BC7_UNORM_SRGB;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_AYUV:							return DXGI_FORMAT_AYUV;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_Y410:							return DXGI_FORMAT_Y410;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_Y416:							return DXGI_FORMAT_Y416;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_NV12:							return DXGI_FORMAT_NV12;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_P010:							return DXGI_FORMAT_P010;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_P016:							return DXGI_FORMAT_P016;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_420_OPAQUE:					return DXGI_FORMAT_420_OPAQUE;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_YUY2:							return DXGI_FORMAT_YUY2;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_Y210:							return DXGI_FORMAT_Y210;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_Y216:							return DXGI_FORMAT_Y216;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_NV11:							return DXGI_FORMAT_NV11;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_AI44:							return DXGI_FORMAT_AI44;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_IA44:							return DXGI_FORMAT_IA44;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_P8:							return DXGI_FORMAT_P8;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_A8P8:							return DXGI_FORMAT_A8P8;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_B4G4R4A4_UNORM:				return DXGI_FORMAT_B4G4R4A4_UNORM;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_P208:							return DXGI_FORMAT_P208;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_V208:							return DXGI_FORMAT_V208;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_V408:							return DXGI_FORMAT_V408;
	case RenderEngine::ORBIT_FORMAT::ORBIT_FORMAT_FORCE_UINT:					return DXGI_FORMAT_FORCE_UINT;
	}

	return DXGI_FORMAT_UNKNOWN;
}
